import Head from "next/head";
import Header from "../components/Header";
import PortfolioChart from "../components/PortfolioChart";
import BuyTokens from "../components/BuyTokens";
import Notice from "../components/Notice";
import Asset from "../components/Asset";
import { BiDotsHorizontalRounded } from "react-icons/bi";
import { AiOutlinePlus } from "react-icons/ai";

const style = {
  wrapper: "w-screen h-screen flex flex-col",
  mainContainer: "w-2/3 h-full m-auto flex mt-16",
  leftMain: "flex flex-col w-3/4 h-full p-6 overflow-y-scroll",
  portfolioAmountContainer: "flex flex-col",
  portfolioAmount: "text-white text-4xl",
  portfolioPercent: "text-white dont-bold text-sm",
  pastHour: "text-gray-400",
  chartContainer:
    "text-5xl flex justify-center w-full h-1/3 text-white mt-11 mb-11",
  buyingPowerContainer:
    "w-full border-t mb-24 border-b h-16 border-[#30363b] flex justify-between item",
  buyingPowerTitle: "text-white font-bold text-lg",
  buyingPowerAmount: "text-white font-bold text-xl",
  notice: "flex border border-[#30363b] mx-11 my-4 p-5 flex-col flex-1",
  noticeContainer: "flex-1",
  noticeTitle: "text-gray-500",
  noticeMessage: "text-white text-bold",
  rightMain:
    "flex flex-col flex-1 h-4/5 bg-[#1E2123] mt-6 rounded-lg overflow-y-scroll noScroll",
  rightMainItem: "flex items-center text-white border-b border-[#30363b]",
  ItemTitle: "",
  moreOptions: "",
};

export default function Home() {
  return (
    <div className={style.wrapper}>
      <Head>
        <title>Robinhood Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className={style.mainContainer}>
        <div className={style.leftMain}>
          <div className={style.portfolioAmountContainer}>
            <div className={style.portfolioAmount}>23 ETH</div>
            <div className={style.portfolioPercent}>
              +0.5%
              <span className={style.pastHour}>Past hour</span>
            </div>
          </div>
          <div>
            <div className={style.chartContainer}>
              <PortfolioChart />
            </div>
          </div>
          <div className={style.buyingPowerContainer}>
            <div className={style.buyingPowerTitle}>Buying Power</div>
            <div className={style.buyingPowerAmount}>$1,000,000</div>
          </div>
          <div className={style.notice}>
            <div className={style.noticeContainer}>
              <div className={style.noticeTitle}>Notice</div>
              <div className={style.noticeMessage}>
                You have no open orders.
              </div>
              <BuyTokens />
            </div>
          </div>
          <Notice />
        </div>
        <div className={style.rightMain}>
          <div className={style.rightMainItem}>
            <div className={style.ItemTitle}>Crypto Currency</div>
            <BiDotsHorizontalRounded className={style.moreOptions} />
          </div>
          <Asset />

          <div className={style.rightMainItem}>
            <div className={style.ItemTitle}>Lists</div>
            <AiOutlinePlus className={style.moreOptions} />
          </div>
        </div>
      </div>
    </div>
  );
}
